export const shakespeare: string[] = [
  "This blessed plot, this earth, this realm, this England, this nurse, this teeming womb of royal kings, feared by their breed and famous by their birth.",
  "There is a tide in the affairs of men, which taken at the flood, leads on to fortune; omitted, all the voyage of their life is bound in shallows.",
  "I know a bank where the wild thyme blows, where oxlips and the nodding violet grows, quite over-canopied with luscious woodbine, with sweet musk-roses and with eglantine.",
  "Our doubts are traitors, and make us lose the good we oft might win, by fearing to attempt the things we know that we could do if we but tried.",
  "What a piece of work is man! How noble in reason, how infinite in faculty! In form and moving how express and admirable! In action how like an angel!",
  "Life's but a walking shadow, a poor player that struts and frets his hour upon the stage, and then is heard no more: it is a tale told by an idiot.",
  "The quality of mercy is not strained; it droppeth as the gentle rain from heaven upon the place beneath. It is twice blest: it blesseth him that gives and him that takes.",
  "Friends, Romans, countrymen, lend me your ears; I come to bury Caesar, not to praise him. The evil that men do lives after them; the good is oft interred with their bones.",
  "But soft, what light through yonder window breaks? It is the east, and Juliet is the sun. Arise, fair sun, and kill the envious moon, who is already sick and pale with grief.",
  "Tomorrow, and tomorrow, and tomorrow, creeps in this petty pace from day to day, to the last syllable of recorded time; and all our yesterdays have lighted fools the way to dusty death.",
  "We few, we happy few, we band of brothers; for he today that sheds his blood with me shall be my brother; be he ne'er so vile, this day shall gentle his condition.",
  "How far that little candle throws his beams! So shines a good deed in a naughty world. When the moon shone, we did not see the candle; so doth the greater glory dim the less.",
  "All the world's a stage, and all the men and women merely players: they have their exits and their entrances; and one man in his time plays many parts, his acts being seven ages.",
  "Cowards die many times before their deaths; the valiant never taste of death but once. Of all the wonders that I yet have heard, it seems to me most strange that men should fear death.",
  "If music be the food of love, play on; give me excess of it, that, surfeiting, the appetite may sicken, and so die. That strain again! It had a dying fall.",
  "O, she doth teach the torches to burn bright! It seems she hangs upon the cheek of night like a rich jewel in an Ethiop's ear; beauty too rich for use, for earth too dear.",
  "Once more unto the breach, dear friends, once more; or close the wall up with our English dead. In peace there's nothing so becomes a man as modest stillness and humility.",
  "What is the city but the people? True, the people are the city. We do pray for mercy, and that same prayer doth teach us all to render the deeds of mercy.",
  "Though this be madness, yet there is method in't. How pregnant sometimes his replies are! A happiness that often madness hits on, which reason and sanity could not so prosperously be delivered of.",
];
