export const KeyboardIcon = () => (
  <svg viewBox="0 0 72 72" className="w-8 h-8">
    <g id="color">
      <path
        transform="translate(0 .408)"
        fill="none"
        d="m5 18.09h62v35.82h-62z"
      />
      <rect
        x="9"
        y="25"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="60"
        y="25"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="16.29"
        y="25"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="23.57"
        y="25"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="30.86"
        y="25"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="38.14"
        y="25"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="45.43"
        y="25"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="52.71"
        y="25"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="20.5"
        y="34.5"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="48.5"
        y="34.5"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="9"
        y="44"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="16"
        y="44"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="53"
        y="44"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="60"
        y="44"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="41.5"
        y="34.5"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="34.5"
        y="34.5"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="27.5"
        y="34.5"
        width="3"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="22.93"
        y="44"
        width="26.14"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="9"
        y="34.5"
        width="7.5"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
      <rect
        x="55.5"
        y="34.5"
        width="7.5"
        height="3"
        fillRule="evenodd"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="2"
      />
    </g>
    <g id="line">
      <path
        fill="none"
        strokeLinecap="round"
        strokeLinejoin="round"
        strokeWidth="3"
        d="m4 17.5h64v36h-64z"
      />
    </g>
  </svg>
);
