version: '3.8'

services:
  typeracingio:
    image: registry.digitalocean.com/typeracingio/typeracingio:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
      - .env.production
    networks:
      - typeracingio-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - typeracingio
    networks:
      - typeracingio-network

volumes:
  certbot-etc:
  certbot-var:

networks:
  typeracingio-network:
    driver: bridge