import { splitmix32 } from "./helpers/splitmix32";

const allegiances = [
 "GSS", // Galactic star ship
 "USS", // United star ship
 "RSS", // Republic star ship
 "CSS", // Confederate star ship
 "ESS", // Empire star ship
 "FSS", // Federation star ship
 "SSS", // Solar star ship
];

const prefixes = [
 "Advocate",
 "Aegis",
 "Agent",
 "Arbiter",
 "Banner",
 "Beacon",
 "Blade",
 "Bringer",
 "Champion",
 "Citizen",
 "Claw",
 "Colossus",
 "Comptroller",
 "Courier",
 "Custodian",
 "Dawn",
 "Defender",
 "Diamond",
 "Distributor",
 "Dream",
 "Emperor",
 "Executor",
 "Eye",
 "Father",
 "Fist",
 "Flame",
 "Force",
 "Forerunner",
 "Gauntlet",
 "Giant",
 "Guardian",
 "Halo",
 "Hammer",
 "Harbinger",
 "Herald",
 "Judge",
 "Keeper",
 "King",
 "Knight",
 "Lady",
 "Legislator",
 "Leviathan",
 "Light",
 "Lord",
 "Magistrate",
 "Marshall",
 "Martyr",
 "Mirror",
 "Mother",
 "Octagon",
 "Panther",
 "Paragon",
 "Pledge",
 "Power",
 "Pride",
 "Prince",
 "Princess",
 "Progenitor",
 "Prophet",
 "Protector",
 "Purveyor",
 "Queen",
 "Ranger",
 "Reign",
 "Shield",
 "Soldier",
 "Song",
 "Soul",
 "Spear",
 "Stallion",
 "Star",
 "Steward",
 "Sword",
 "Titan",
 "Triumph",
 "Warrior",
 "Whisper",
 "Will",
 "Wings",
];

const suffixes = [
 "of Allegiance",
 "of Audacity",
 "of Authority",
 "of Battle",
 "of Benevolence",
 "of Conquest",
 "of Conviction",
 "of Conviviality",
 "of Courage",
 "of Dawn",
 "of Destiny",
 "of Destruction",
 "of Equality",
 "of Eternity",
 "of Fortitude",
 "of Freedom",
 "of Glory",
 "of Gold",
 "of Honour",
 "of Humankind",
 "of Integrity",
 "of Iron",
 "of Judgement",
 "of Justice",
 "of Liberty",
 "of Mercy",
 "of Midnight",
 "of Morning",
 "of Opportunity",
 "of Peace",
 "of Perseverance",
 "of Pride",
 "of Redemption",
 "of Science",
 "of Serenity",
 "of Starlight",
 "of Steel",
 "of Supremacy",
 "of the Stars",
 "of Truth",
 "of Twilight",
 "of Victory",
 "of Vigilance",
 "of War",
 "of Wrath",
];

export const generateRandomName = () => {
 const rng = splitmix32(Date.now());
 const allegiance =
  allegiances[Math.floor(rng.next() * allegiances.length)];
 const prefix =
  prefixes[Math.floor(rng.next() * prefixes.length)];
 const suffix =
  suffixes[Math.floor(rng.next() * suffixes.length)];
 return `${allegiance} ${prefix} ${suffix}`;
};
